export enum HTTP_ERROR_CODE {
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    BAD_REQUEST = "BAD_REQUEST",
}

export enum MOVIE_ERROR_CODE {
    MOVIE_ALREADY_EXISTS = "MOVIE_ALREADY_EXISTS",
    INVALID_INPUT_GENRE = "INVALID_INPUT_GENRE",
}
